// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDv43Y7TNVjNEB-AdSh2iRZ1BaUxyFykQ',
    appId: '1:1004422281770:web:122fd5fb07a5d9ef796153',
    messagingSenderId: '1004422281770',
    projectId: 'serpent-arena-f0494',
    authDomain: 'serpent-arena-f0494.firebaseapp.com',
    storageBucket: 'serpent-arena-f0494.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTAlus2qF7tbCysVPXy0ECwnc4XEOtcPg',
    appId: '1:1004422281770:android:a3aeecb47743ebc9796153',
    messagingSenderId: '1004422281770',
    projectId: 'serpent-arena-f0494',
    storageBucket: 'serpent-arena-f0494.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoOF1zWy5Zo2R0HrgX23sdM1zGFuqzuBo',
    appId: '1:1004422281770:ios:9232a0872ec082bb796153',
    messagingSenderId: '1004422281770',
    projectId: 'serpent-arena-f0494',
    storageBucket: 'serpent-arena-f0494.firebasestorage.app',
    iosBundleId: 'com.cpp.serpentarena.serpentArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoOF1zWy5Zo2R0HrgX23sdM1zGFuqzuBo',
    appId: '1:1004422281770:ios:9232a0872ec082bb796153',
    messagingSenderId: '1004422281770',
    projectId: 'serpent-arena-f0494',
    storageBucket: 'serpent-arena-f0494.firebasestorage.app',
    iosBundleId: 'com.cpp.serpentarena.serpentArena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDv43Y7TNVjNEB-AdSh2iRZ1BaUxyFykQ',
    appId: '1:1004422281770:web:7059ffe82528f1d8796153',
    messagingSenderId: '1004422281770',
    projectId: 'serpent-arena-f0494',
    authDomain: 'serpent-arena-f0494.firebaseapp.com',
    storageBucket: 'serpent-arena-f0494.firebasestorage.app',
  );
}
